[workspace]
members = [".", "client", "proc-macro", "test-node"]

[package]
name = "substrate-subxt"
version = "0.11.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/paritytech/substrate-subxt"
documentation = "https://docs.rs/substrate-subxt"
homepage = "https://www.parity.io/"
description = "Submit extrinsics (transactions) to a substrate node via RPC"
keywords = ["parity", "substrate", "blockchain"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[features]
client = ["substrate-subxt-client"]

[dependencies]
log = "0.4.11"
thiserror = "1.0.20"
futures = "0.3.5"
jsonrpsee = { version = "0.1.0", features = ["ws"] }
num-traits = { version = "0.2.12", default-features = false }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
url = "2.1.1"
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive", "full"] }

frame-metadata = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "frame-metadata" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "frame-support" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "sp-runtime" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "sp-version" }
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "pallet-indices" }
hex = "0.4.2"
sp-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "sp-rpc" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "sp-core" }
sc-rpc-api = { sc-rpc-api = { package = "sc-rpc-api", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }, package = "sc-rpc-api" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "sp-transaction-pool" }
substrate-subxt-client = { version = "0.3.0", path = "client", optional = true }
substrate-subxt-proc-macro = { version = "0.11.0", path = "proc-macro" }

[dev-dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
env_logger = "0.7.1"
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "frame-system" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "pallet-balances" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "sp-keyring" }
substrate-subxt-client = { version = "0.3.0", path = "client" }
tempdir = "0.3.7"
test-node = { path = "test-node" }
wabt = "0.10.0"
